import {Application} from "express";
import swaggerUi from 'swagger-ui-express'
import {SwaggerOptions} from "swagger-ui-express";


export class SwaggerConfig{
    app:Application
    options:SwaggerOptions = {
      // List of files to be processed.
      apis: ['./ice-cream/index.js', './cookies/index.js'],
      // You can also set globs for your apis
      // e.g. './routes/*.js'
      basePath: '/',
      swaggerDefinition: {
        info: {
          description: 'Test API with autogenerated swagger doc',
          swagger: '2.0',
          title: 'Dessert API',
          version: '1.0.0',
        },
      },
    }

    constructor(app:Application) {
        this.app = app
    }

    initiateSwagger= () => {
        this.app.use("/docs",
          swaggerUi.serve,
          swaggerUi.setup(undefined, {
            swaggerOptions: {
              url: "/swagger.json",
            },
          })
);
    }
}